-- PetZone Demo Seed Data
-- Run AFTER schema.sql
-- Passwords are bcrypt hashes of the plain-text shown in comments
-- ============================================================
USE `petzone`;

-- ============================================================
-- DEMO USERS
-- admin   / Admin@1234
-- vet1    / Vet@11234
-- client1 / Client@1234
-- ============================================================
INSERT INTO `users` (`firstname`,`lastname`,`Username`,`Email`,`password`,`accountType`) VALUES
('Admin','User',   'admin',   'admin@petzone.com',   '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'Admin'),
('Sarah', 'Jones',  'vet1',    'vet1@petzone.com',    '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'Employee'),
('Mohamed','Ali',  'client1', 'client1@petzone.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'Client');

-- NOTE: the hash above is the Laravel/PHP default test hash for "password"
-- Replace with real bcrypt hashes generated by:
--   echo password_hash('Admin@1234', PASSWORD_BCRYPT);

-- ============================================================
-- DEMO PETS
-- ============================================================
INSERT INTO `patients` (`addedBy`,`petname`,`species`,`breed`,`gender`,`age`,`weight`,`color`,`notes`) VALUES
('client1','Milo',  'Cat','Persian',     'Male',   3, 4.50, 'White',  'Indoor cat, healthy'),
('client1','Buddy', 'Dog','Golden Retriever','Male',5, 28.00,'Golden', 'Friendly, needs regular grooming'),
('client1','Luna',  'Cat','Siamese',     'Female', 2, 3.80, 'Cream',  'Shy but gentle');

-- ============================================================
-- DEMO APPOINTMENTS
-- ============================================================
INSERT INTO `appointments` (`petOwner`,`EmployeeName`,`petname`,`service_type`,`aDate`,`price`,`status`) VALUES
('client1','vet1','Milo', 'Vaccination',    DATE_ADD(CURDATE(), INTERVAL 3 DAY),  150.00,'Confirmed'),
('client1','vet1','Buddy','General Checkup', DATE_ADD(CURDATE(), INTERVAL 7 DAY), 100.00,'Pending'),
('client1','vet1','Luna', 'Medication',      DATE_ADD(CURDATE(), INTERVAL 14 DAY),300.00,'Pending');

-- ============================================================
-- DEMO HEALTH RECORDS
-- ============================================================
INSERT INTO `health_records` (`pet_id`,`petname`,`addedBy`,`record_type`,`title`,`description`,`vet_name`,`visit_date`,`next_visit_date`) VALUES
(1,'Milo', 'client1','Vaccination','Annual Vaccines',    'Rabies + FVRCP combo vaccine given','Dr. Sarah Jones', DATE_SUB(CURDATE(),INTERVAL 6 MONTH), DATE_ADD(CURDATE(),INTERVAL 6 MONTH)),
(2,'Buddy','client1','Checkup',    'Routine Health Check','All vitals normal, weight stable',  'Dr. Sarah Jones', DATE_SUB(CURDATE(),INTERVAL 3 MONTH), DATE_ADD(CURDATE(),INTERVAL 9 MONTH)),
(2,'Buddy','client1','Medication', 'Flea Treatment',     'Frontline Plus applied',             'Dr. Sarah Jones', DATE_SUB(CURDATE(),INTERVAL 1 MONTH), DATE_ADD(CURDATE(),INTERVAL 2 MONTH));

-- ============================================================
-- DEMO PRODUCTS
-- ============================================================
INSERT INTO `products` (`name`,`description`,`price`,`category`,`image`,`stock`) VALUES
('Premium Cat Food',     'High-protein dry food for adult cats. Grain-free formula.',         89.99,  'Food',        'catFood.jpg',   50),
('Luxury Cat Bed',       'Soft, washable plush bed with raised rim for neck support.',        199.99, 'Accessories', 'catBed.jpeg',   20),
('Premium Dog Food',     'Balanced nutrition dry food for adult dogs. All-natural ingredients.',119.99,'Food',       'dogFood.jpeg',  40),
('Orthopedic Dog Bed',   'Memory foam bed for joint support. Ideal for larger breeds.',       349.99, 'Accessories', 'dogBed.jpeg',   15),
('Portable Pet Carrier', 'Airline-approved carrier cage. Ventilated, durable, easy to clean.',279.99, 'Accessories', 'cage.jpeg',     25),
('Pet Vitamins',         'Daily multivitamin chews for cats and dogs. Chicken flavored.',     69.99,  'Medicine',    NULL,            60),
('Interactive Toy Set',  'Set of 3 stimulating toys to keep your pet entertained.',           49.99,  'Toys',        NULL,            80);
